import type { PluginKindDefinition } from "./shared";
import {
  executorRef,
  executorReferenceArrayItem,
  inputArrayItem,
  nftSetTargetFields,
  stringArrayField,
} from "./shared";

export const executorPluginDefinitions: PluginKindDefinition[] = [
  {
    kind: "sequence",
    type: "executor",
    name: "Sequence",
    description: "按顺序编排 matcher 与 executor，是最常用入口执行器",
    icon: "GitBranch",
    configSchema: [
      {
        key: "args",
        description: "定义 sequence 的规则链。",
        label: "规则链",
        type: "array",
        required: true,
        placeholder: "$cache_main\nmatches: !$has_resp, exec: $forward_main",
        item: {
          type: "object",
          label: "规则",
          summaryFields: ["exec"],
          fields: [
            {
              key: "matches",
              description: "定义当前规则的匹配条件。",
              label: "匹配条件",
              type: "array",
              placeholder: "$has_resp\nqname domain:example.com\n!$blocked",
              itemOptions: [
                {
                  optionKey: "matcher_ref",
                  type: "reference",
                  label: "引用 matcher",
                  referenceTypes: ["matcher"],
                  referencePrefix: "$",
                  allowInvert: true,
                  placeholder: "has_resp",
                },
                {
                  optionKey: "input",
                  type: "text",
                  label: "输入值",
                  placeholder: "qname domain:example.com",
                },
              ],
            },
            {
              key: "exec",
              description: "定义规则命中后要执行的动作。",
              label: "执行动作",
              type: "text",
              placeholder: "$forward_main / accept / reject 3 / jump seq_tag",
            },
          ],
        },
      },
    ],
  },
  {
    kind: "forward",
    type: "executor",
    name: "Forward",
    description: "向一个或多个上游 DNS 发起查询",
    icon: "ArrowUpRight",
    configSchema: [
      {
        key: "concurrent",
        description: "定义多上游模式下的并发查询扇出数。",
        label: "并发上游数",
        type: "number",
        default: 1,
      },
      {
        key: "upstreams",
        description: "定义一个或多个上游目标。",
        label: "上游列表",
        type: "array",
        required: true,
        placeholder: "udp://1.1.1.1:53",
        item: {
          type: "object",
          summaryFields: ["tag", "addr"],
          fields: [
            {
              key: "tag",
              description: "为单个上游提供日志标识，便于排查多上游竞争结果。",
              label: "上游标识",
              type: "text",
              placeholder: "cf_udp",
            },
            {
              key: "addr",
              description: "定义上游地址、协议类型以及目标主机。",
              label: "上游地址",
              type: "text",
              required: true,
              placeholder: "udp://1.1.1.1:53",
            },
            {
              key: "dial_addr",
              description:
                "指定实际连接 IP，同时保留 addr 中的主机名用于 SNI、Host 和证书校验。",
              label: "拨号 IP",
              type: "text",
              placeholder: "203.0.113.53",
            },
            {
              key: "port",
              description: "覆盖协议默认端口。",
              label: "端口覆盖",
              type: "number",
              placeholder: "443",
            },
            {
              key: "bootstrap",
              description: "为域名型上游提供引导解析服务器。",
              label: "Bootstrap",
              type: "text",
              placeholder: "8.8.8.8:53",
            },
            {
              key: "bootstrap_version",
              description: "指定 bootstrap 优先使用 IPv4 或 IPv6。",
              label: "Bootstrap IP 版本",
              type: "select",
              options: [
                { label: "IPv4", value: "4" },
                { label: "IPv6", value: "6" },
              ],
            },
            {
              key: "socks5",
              description: "为上游连接指定 SOCKS5 代理。",
              label: "SOCKS5 代理",
              type: "text",
              placeholder: "user:pass@127.0.0.1:1080",
            },
            {
              key: "idle_timeout",
              description: "定义连接池空闲连接保留时间。",
              label: "连接空闲超时(秒)",
              type: "number",
              placeholder: "30",
            },
            {
              key: "max_conns",
              description: "定义连接池连接上限。",
              label: "最大连接数",
              type: "number",
              placeholder: "256",
            },
            {
              key: "insecure_skip_verify",
              description: "控制是否跳过 TLS 证书校验。",
              label: "跳过 TLS 校验",
              type: "switch",
              default: false,
            },
            {
              key: "timeout",
              description: "定义单次上游查询超时。",
              label: "查询超时",
              type: "duration",
              placeholder: "3s",
            },
            {
              key: "enable_pipeline",
              description: "控制 TCP 或 DoT 流水线。",
              label: "启用 Pipeline",
              type: "switch",
            },
            {
              key: "enable_http3",
              description: "控制 DoH 是否使用 HTTP/3。",
              label: "启用 HTTP/3",
              type: "switch",
              default: false,
            },
            {
              key: "so_mark",
              description: "设置 Linux SO_MARK。",
              label: "SO_MARK",
              type: "number",
              placeholder: "100",
            },
            {
              key: "bind_to_device",
              description: "设置 Linux SO_BINDTODEVICE。",
              label: "绑定网卡",
              type: "text",
              placeholder: "eth0",
            },
          ],
        },
      },
      {
        key: "short_circuit",
        description: "控制在拿到成功上游响应后，是否立即停止后续 executor 链。",
        label: "成功后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "cache",
    type: "executor",
    name: "Cache",
    description: "TTL 感知缓存，支持负缓存、lazy cache 与持久化",
    icon: "Database",
    configSchema: [
      {
        key: "size",
        description: "定义缓存最大条目数。",
        label: "最大条目数",
        type: "number",
        default: 1024,
      },
      {
        key: "lazy_cache_ttl",
        description: "为正向成功响应启用 lazy cache。",
        label: "Lazy Cache TTL(秒)",
        type: "number",
      },
      {
        key: "dump_file",
        description: "指定缓存持久化文件路径。",
        label: "持久化文件",
        type: "text",
        placeholder: "./dns_cache.dump",
      },
      {
        key: "dump_interval",
        description: "定义缓存定期落盘周期。",
        label: "落盘周期(秒)",
        type: "number",
        default: 600,
      },
      {
        key: "short_circuit",
        description: "控制缓存命中后是否立即结束后续执行。",
        label: "命中后停止后续执行",
        type: "switch",
      },
      {
        key: "cache_negative",
        description: "控制是否缓存 NXDOMAIN 与 NODATA。",
        label: "缓存负响应",
        type: "switch",
      },
      {
        key: "max_negative_ttl",
        description: "定义负缓存 TTL 上限。",
        label: "负缓存 TTL 上限",
        type: "number",
        default: 300,
      },
      {
        key: "negative_ttl_without_soa",
        description: "定义无 SOA 负响应的回退 TTL。",
        label: "无 SOA 负缓存 TTL",
        type: "number",
        default: 60,
      },
      {
        key: "max_positive_ttl",
        description: "定义正响应 TTL 上限。",
        label: "正响应 TTL 上限",
        type: "number",
      },
      {
        key: "ecs_in_key",
        description: "控制 ECS scope 是否参与缓存键计算。",
        label: "ECS 参与缓存键",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "fallback",
    type: "executor",
    name: "Fallback",
    description: "主路径失败或过慢时切换到备用执行器",
    icon: "GitBranch",
    configSchema: [
      executorRef("primary", "主执行器", true, undefined, "指定主执行器。"),
      executorRef(
        "secondary",
        "备用执行器",
        true,
        undefined,
        "指定备用执行器。",
      ),
      {
        key: "threshold",
        description: "定义主路径超时或延迟判定阈值。",
        label: "接管阈值(ms)",
        type: "number",
        default: 0,
      },
      {
        key: "always_standby",
        description: "控制备用路径是否与主路径同时待命。",
        label: "备用路径并行待命",
        type: "switch",
        default: false,
      },
      {
        key: "short_circuit",
        description:
          "控制在主/备路径选出最终响应后，是否立即停止后续 executor 链。",
        label: "成功后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "hosts",
    type: "executor",
    name: "Hosts",
    description: "按域名规则直接返回静态 A / AAAA",
    icon: "FileText",
    configSchema: [
      stringArrayField(
        "entries",
        "内联 hosts 规则",
        "router.local 192.168.1.1\ndomain:svc.local 10.0.0.10",
        false,
        "定义内联 hosts 规则。",
      ),
      stringArrayField(
        "files",
        "hosts 文件",
        "/etc/forgedns/hosts.txt",
        false,
        "指定外部 hosts 规则文件列表。",
      ),
      {
        key: "short_circuit",
        description: "命中并生成本地应答后，是否立即停止后续 executor 链。",
        label: "命中后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "arbitrary",
    type: "executor",
    name: "Arbitrary",
    description: "加载静态 DNS 记录并在命中时构造应答",
    icon: "FileQuestion",
    configSchema: [
      stringArrayField(
        "rules",
        "静态记录",
        'example.com. 60 IN TXT "hello world"\nwww.example.com. 120 IN A 192.0.2.10',
        false,
        "定义内联静态记录列表。",
      ),
      stringArrayField(
        "files",
        "记录文件",
        "/etc/forgedns/zone.txt",
        false,
        "指定静态记录文件列表。",
      ),
      {
        key: "short_circuit",
        description: "命中并生成本地响应后，是否立即停止后续 executor 链。",
        label: "命中后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "redirect",
    type: "executor",
    name: "Redirect",
    description: "改写请求域名，并在返回阶段补回 CNAME",
    icon: "Pencil",
    configSchema: [
      stringArrayField(
        "rules",
        "重定向规则",
        "full:old.example.com new.example.net\ndomain:legacy.example.com modern.example.net",
        false,
        "定义内联重定向规则。",
      ),
      stringArrayField(
        "files",
        "规则文件",
        "/etc/forgedns/redirect.txt",
        false,
        "指定外部重定向规则文件列表。",
      ),
    ],
  },
  {
    kind: "ecs_handler",
    type: "executor",
    name: "ECS Handler",
    description: "处理 EDNS Client Subnet 的保留、注入和回程清理",
    icon: "Globe",
    configSchema: [
      {
        key: "forward",
        description: "控制是否保留客户端请求中已有的 ECS。",
        label: "保留客户端 ECS",
        type: "switch",
        default: false,
      },
      {
        key: "send",
        description: "控制在请求缺少 ECS 时，是否根据来源地址自动补充 ECS。",
        label: "缺失时发送 ECS",
        type: "switch",
        default: false,
      },
      {
        key: "preset",
        description: "指定固定的 ECS 来源地址。",
        label: "预设 ECS 地址",
        type: "text",
        placeholder: "203.0.113.10",
      },
      {
        key: "mask4",
        description: "指定 IPv4 ECS 前缀长度。",
        label: "IPv4 前缀长度",
        type: "number",
        default: 24,
      },
      {
        key: "mask6",
        description: "指定 IPv6 ECS 前缀长度。",
        label: "IPv6 前缀长度",
        type: "number",
        default: 48,
      },
    ],
  },
  {
    kind: "forward_edns0opt",
    type: "executor",
    name: "Forward EDNS0 Opt",
    description: "把指定 EDNS0 option 从请求转发到响应",
    icon: "ArrowUpRight",
    configSchema: [
      stringArrayField(
        "codes",
        "Option Code",
        "10\n12",
        false,
        "定义允许从请求复制到响应中的 EDNS0 option code 集合。",
      ),
    ],
  },
  {
    kind: "ttl",
    type: "executor",
    name: "TTL",
    description: "固定、抬高或限制响应 TTL",
    icon: "Clock",
    configSchema: [
      {
        key: "fix",
        description: "将所有响应 TTL 固定为同一个值。",
        label: "固定 TTL",
        type: "number",
      },
      {
        key: "min",
        description: "定义 TTL 下限。",
        label: "TTL 下限",
        type: "number",
      },
      {
        key: "max",
        description: "定义 TTL 上限。",
        label: "TTL 上限",
        type: "number",
      },
    ],
  },
  {
    kind: "prefer_ipv4",
    type: "executor",
    name: "Prefer IPv4",
    description: "双栈优选器，偏好 A 记录并抑制可替代的 AAAA 请求",
    icon: "Shuffle",
    configSchema: [
      {
        key: "cache",
        description: "控制是否缓存 preferred 类型存在状态。",
        label: "缓存偏好状态",
        type: "switch",
        default: true,
      },
      {
        key: "cache_ttl",
        description: "定义 preferred 状态缓存时长。",
        label: "偏好状态缓存 TTL(秒)",
        type: "number",
        default: 3600,
      },
    ],
  },
  {
    kind: "prefer_ipv6",
    type: "executor",
    name: "Prefer IPv6",
    description: "双栈优选器，偏好 AAAA 记录并抑制可替代的 A 请求",
    icon: "Shuffle",
    configSchema: [
      {
        key: "cache",
        description: "控制是否缓存 preferred 类型存在状态。",
        label: "缓存偏好状态",
        type: "switch",
        default: true,
      },
      {
        key: "cache_ttl",
        description: "定义 preferred 状态缓存时长。",
        label: "偏好状态缓存 TTL(秒)",
        type: "number",
        default: 3600,
      },
    ],
  },
  {
    kind: "black_hole",
    type: "executor",
    name: "Black Hole",
    description: "对命中的 A / AAAA 请求直接返回预设地址",
    icon: "Ban",
    configSchema: [
      stringArrayField(
        "ips",
        "返回地址",
        "0.0.0.0\n::",
        false,
        "定义本地合成返回地址集合。",
      ),
      {
        key: "short_circuit",
        description: "命中并生成本地应答后，是否立即停止后续 executor 链。",
        label: "命中后停止后续执行",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "drop_resp",
    type: "executor",
    name: "Drop Response",
    description: "清空当前上下文中的响应",
    icon: "Ban",
    configSchema: [],
  },
  {
    kind: "reverse_lookup",
    type: "executor",
    name: "Reverse Lookup",
    description: "缓存 IP 到域名关系，并可选直接处理 PTR 查询",
    icon: "Database",
    configSchema: [
      {
        key: "size",
        description: "定义反查缓存容量上限。",
        label: "反查缓存容量",
        type: "number",
        default: 65535,
      },
      {
        key: "handle_ptr",
        description: "控制是否直接用反查缓存响应 PTR 请求。",
        label: "直接响应 PTR",
        type: "switch",
        default: false,
      },
      {
        key: "ttl",
        description: "定义 IP 到域名映射的缓存 TTL。",
        label: "映射 TTL(秒)",
        type: "number",
        default: 7200,
      },
    ],
  },
  {
    kind: "query_summary",
    type: "executor",
    name: "Query Summary",
    description: "在后续链路执行完后输出紧凑查询摘要",
    icon: "FileText",
    configSchema: [
      {
        key: "msg",
        description: "定义摘要日志标题。",
        label: "日志标题",
        type: "text",
        placeholder: "main pipeline",
        default: "query summary",
      },
    ],
  },
  {
    kind: "query_recorder",
    type: "executor",
    name: "Query Recorder",
    description: "将请求、响应和 sequence 路径事件持久化到 SQLite",
    icon: "Database",
    configSchema: [
      {
        key: "path",
        description: "指定当前 recorder 的 SQLite 文件路径。",
        label: "SQLite 文件",
        type: "text",
        required: true,
        placeholder: "./data/query-recorder-main.sqlite",
      },
      {
        key: "queue_size",
        description: "定义热路径到后台写线程的有界队列大小。",
        label: "队列大小",
        type: "number",
        default: 8192,
      },
      {
        key: "batch_size",
        description: "定义后台批量写入 SQLite 的单批记录数。",
        label: "批量写入条数",
        type: "number",
        default: 256,
      },
      {
        key: "flush_interval_ms",
        description: "定义后台写线程的批量 flush 间隔。",
        label: "Flush 间隔(ms)",
        type: "number",
        default: 200,
      },
      {
        key: "memory_tail",
        description: "定义最近记录的内存 tail 长度，用于 stream?tail=n 回放。",
        label: "内存 Tail 长度",
        type: "number",
        default: 1024,
      },
      {
        key: "retention_days",
        description: "定义日志保留天数；过期数据会被定时实际删除。",
        label: "保留天数",
        type: "number",
        default: 7,
      },
      {
        key: "cleanup_interval_hours",
        description: "定义过期清理任务的执行周期。",
        label: "清理周期(小时)",
        type: "number",
        default: 1,
      },
    ],
  },
  {
    kind: "metrics_collector",
    type: "executor",
    name: "Metrics Collector",
    description: "收集轻量级请求计数与延时指标并导出 Prometheus 格式",
    icon: "Gauge",
    configSchema: [
      {
        key: "name",
        description: "定义当前指标收集器的名称标签。",
        label: "指标名称",
        type: "text",
        default: "default",
      },
    ],
  },
  {
    kind: "debug_print",
    type: "executor",
    name: "Debug Print",
    description: "打印请求与响应对象，便于调试",
    icon: "FileText",
    configSchema: [
      {
        key: "msg",
        description: "定义日志输出标题。",
        label: "日志标题",
        type: "text",
        default: "debug print",
      },
    ],
  },
  {
    kind: "sleep",
    type: "executor",
    name: "Sleep",
    description: "异步延迟，用于测试和策略实验",
    icon: "Clock",
    configSchema: [
      {
        key: "duration",
        description: "定义当前请求在该执行器上的额外异步等待时间。",
        label: "延迟(ms)",
        type: "number",
        default: 0,
      },
    ],
  },
  {
    kind: "http_request",
    type: "executor",
    name: "HTTP Request",
    description: "向外部 HTTP/HTTPS 服务发送 webhook、审计或联动请求",
    icon: "Globe",
    configSchema: [
      {
        key: "method",
        description: "指定 HTTP 方法，例如 GET、POST、PUT、PATCH、DELETE。",
        label: "HTTP 方法",
        type: "select",
        required: true,
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "PATCH", value: "PATCH" },
          { label: "DELETE", value: "DELETE" },
        ],
        default: "POST",
      },
      {
        key: "url",
        description: "目标 URL。",
        label: "目标 URL",
        type: "text",
        required: true,
        placeholder: "https://hooks.example.com/dns",
      },
      {
        key: "phase",
        description:
          "控制请求在下游 executor 之前发送，还是在下游执行完成后发送。",
        label: "触发阶段",
        type: "select",
        options: [
          { label: "Before", value: "before" },
          { label: "After", value: "after" },
        ],
        default: "after",
      },
      {
        key: "async",
        description:
          "控制使用异步后台队列发送，还是在当前请求路径同步等待 HTTP 完成。",
        label: "异步发送",
        type: "switch",
        default: true,
      },
      {
        key: "timeout",
        description: "限制单次 HTTP 调用的总超时时间。",
        label: "超时",
        type: "duration",
        default: "5s",
      },
      {
        key: "error_mode",
        description: "控制 HTTP 调用失败后的处理方式。",
        label: "错误处理",
        type: "select",
        options: [
          { label: "Continue", value: "continue" },
          { label: "Stop", value: "stop" },
          { label: "Fail", value: "fail" },
        ],
        default: "continue",
      },
      {
        key: "headers",
        description: "附加 HTTP 请求头。",
        label: "请求头",
        type: "record",
        keyPlaceholder: "X-Qname",
        valuePlaceholder: "${qname}",
      },
      {
        key: "query_params",
        description: "把额外参数追加到 URL query 上。",
        label: "Query 参数",
        type: "record",
        keyPlaceholder: "qname",
        valuePlaceholder: "${qname}",
      },
      {
        key: "body",
        description: "原始字符串请求体。",
        label: "原始 Body",
        type: "textarea",
        placeholder: "qname=${qname}",
      },
      {
        key: "json",
        description: "以 JSON 方式发送请求体。",
        label: "JSON Body",
        type: "json",
        placeholder: '{"qname":"${qname}","client_ip":"${client_ip}"}',
      },
      {
        key: "form",
        description: "以 application/x-www-form-urlencoded 方式发送表单。",
        label: "表单 Body",
        type: "record",
        keyPlaceholder: "qname",
        valuePlaceholder: "${qname}",
      },
      {
        key: "content_type",
        description: "为原始 args.body 指定 Content-Type。",
        label: "Content-Type",
        type: "text",
      },
      {
        key: "socks5",
        description: "指定 SOCKS5 代理。",
        label: "SOCKS5 代理",
        type: "text",
        placeholder: "127.0.0.1:1080",
      },
      {
        key: "insecure_skip_verify",
        description: "是否跳过 HTTPS 证书校验。",
        label: "跳过 HTTPS 证书校验",
        type: "switch",
        default: false,
      },
      {
        key: "max_redirects",
        description: "限制最多跟随多少次重定向。",
        label: "最大重定向次数",
        type: "number",
        default: 5,
      },
      {
        key: "queue_size",
        description: "异步模式下后台发送队列的容量。",
        label: "异步队列大小",
        type: "number",
        default: 256,
      },
    ],
  },
  {
    kind: "script",
    type: "executor",
    name: "Script",
    description: "执行外部命令，并注入 DnsContext 中的稳定字段",
    icon: "Settings",
    configSchema: [
      {
        key: "command",
        description: "要执行的命令路径或命令名。",
        label: "命令",
        type: "text",
        required: true,
        placeholder: "bash",
      },
      stringArrayField(
        "args",
        "命令参数",
        "/opt/forgedns/notify.sh\n${qname}",
        false,
        "传给命令的参数数组。",
      ),
      {
        key: "env",
        description: "追加到子进程环境变量中的键值对。",
        label: "环境变量",
        type: "record",
        keyPlaceholder: "FDNS_QNAME",
        valuePlaceholder: "${qname}",
      },
      {
        key: "cwd",
        description: "指定脚本运行时的工作目录。",
        label: "工作目录",
        type: "text",
        placeholder: "/opt/forgedns",
      },
      {
        key: "timeout",
        description: "限制单次脚本执行时长。",
        label: "超时",
        type: "duration",
        default: "5s",
      },
      {
        key: "error_mode",
        description: "控制脚本失败或超时后的处理方式。",
        label: "错误处理",
        type: "select",
        options: [
          { label: "Continue", value: "continue" },
          { label: "Stop", value: "stop" },
          { label: "Fail", value: "fail" },
        ],
        default: "continue",
      },
      {
        key: "max_output_bytes",
        description: "限制 stdout / stderr 的捕获长度，超过部分只做截断标记。",
        label: "最大输出捕获字节",
        type: "number",
        default: 4096,
      },
    ],
  },
  {
    kind: "ipset",
    type: "executor",
    name: "IPSet",
    description: "把响应中的 IP 写入 Linux ipset",
    icon: "MapPin",
    configSchema: [
      {
        key: "set_name4",
        description: "指定写入 IPv4 地址的 ipset 名称。",
        label: "IPv4 ipset 名称",
        type: "text",
      },
      {
        key: "set_name6",
        description: "指定写入 IPv6 地址的 ipset 名称。",
        label: "IPv6 ipset 名称",
        type: "text",
      },
      {
        key: "mask4",
        description: "指定 IPv4 地址写入 ipset 时使用的前缀长度。",
        label: "IPv4 前缀长度",
        type: "number",
        default: 24,
      },
      {
        key: "mask6",
        description: "指定 IPv6 地址写入 ipset 时使用的前缀长度。",
        label: "IPv6 前缀长度",
        type: "number",
        default: 32,
      },
    ],
  },
  {
    kind: "nftset",
    type: "executor",
    name: "NFTSet",
    description: "把响应 IP 写入 Linux nftables set",
    icon: "MapPin",
    configSchema: [
      {
        key: "ipv4",
        description: "定义 IPv4 目标 nftables set。",
        label: "IPv4 目标",
        type: "object",
        fields: nftSetTargetFields,
        summaryFields: ["table_family", "table_name", "set_name"],
      },
      {
        key: "ipv6",
        description: "定义 IPv6 目标 nftables set。",
        label: "IPv6 目标",
        type: "object",
        fields: nftSetTargetFields.map((field) =>
          field.key === "table_family"
            ? { ...field, placeholder: "ip6" }
            : field.key === "set_name"
              ? { ...field, placeholder: "dns_v6" }
              : field,
        ),
        summaryFields: ["table_family", "table_name", "set_name"],
      },
      {
        key: "table_family4",
        description: "兼容写法下定义 IPv4 的 nftables 表 family。",
        label: "IPv4 表 family",
        type: "text",
      },
      {
        key: "table_name4",
        description: "兼容写法下定义 IPv4 的 nftables 表名。",
        label: "IPv4 表名",
        type: "text",
      },
      {
        key: "set_name4",
        description: "兼容写法下定义 IPv4 的 set 名称。",
        label: "IPv4 set 名称",
        type: "text",
      },
      {
        key: "mask4",
        description: "兼容写法下定义 IPv4 前缀长度。",
        label: "IPv4 前缀长度",
        type: "number",
      },
      {
        key: "table_family6",
        description: "兼容写法下定义 IPv6 的 nftables 表 family。",
        label: "IPv6 表 family",
        type: "text",
      },
      {
        key: "table_name6",
        description: "兼容写法下定义 IPv6 的 nftables 表名。",
        label: "IPv6 表名",
        type: "text",
      },
      {
        key: "set_name6",
        description: "兼容写法下定义 IPv6 的 set 名称。",
        label: "IPv6 set 名称",
        type: "text",
      },
      {
        key: "mask6",
        description: "兼容写法下定义 IPv6 前缀长度。",
        label: "IPv6 前缀长度",
        type: "number",
      },
    ],
  },
  {
    kind: "ros_address_list",
    type: "executor",
    name: "RouterOS Address List",
    description: "把应答 IP 同步到 RouterOS address-list",
    icon: "Network",
    configSchema: [
      {
        key: "address",
        description: "指定 RouterOS API 服务地址，通常写为 host:port。",
        label: "RouterOS API 地址",
        type: "text",
        required: true,
        placeholder: "172.16.1.1:8728",
      },
      {
        key: "username",
        description: "指定 RouterOS API 登录用户名。",
        label: "用户名",
        type: "text",
        required: true,
      },
      {
        key: "password",
        description: "指定 RouterOS API 登录密码。",
        label: "密码",
        type: "text",
        required: true,
      },
      {
        key: "async",
        description: "控制地址写入行为是否采用异步方式。",
        label: "异步提交",
        type: "switch",
        default: true,
      },
      {
        key: "address_list4",
        description: "指定 IPv4 地址写入的目标 address-list 名称。",
        label: "IPv4 Address List",
        type: "text",
      },
      {
        key: "address_list6",
        description: "指定 IPv6 地址写入的目标 address-list 名称。",
        label: "IPv6 Address List",
        type: "text",
      },
      {
        key: "comment_prefix",
        description: "指定插件写入 RouterOS 条目时使用的注释前缀。",
        label: "注释前缀",
        type: "text",
        default: "fdns",
      },
      {
        key: "persistent",
        description: "定义需要长期保留的静态地址集合。",
        label: "常驻地址",
        type: "object",
        fields: [
          stringArrayField(
            "ips",
            "IP / CIDR",
            "1.1.1.1\n100.64.1.0/24",
            false,
            "以内联方式声明常驻 IP 或 CIDR 网段。",
            {
              type: "text",
              label: "输入值",
              placeholder: "1.1.1.1",
            },
          ),
          stringArrayField(
            "files",
            "文件",
            "/etc/forgedns/persistent_ips.txt",
            false,
            "从外部文件加载常驻地址集合。",
            {
              type: "text",
              label: "输入值",
              placeholder: "/etc/forgedns/persistent_ips.txt",
            },
          ),
        ],
      },
      {
        key: "min_ttl",
        description: "定义动态地址项允许使用的最小 TTL。",
        label: "动态项最小 TTL",
        type: "number",
        default: 60,
      },
      {
        key: "max_ttl",
        description: "定义动态地址项允许使用的最大 TTL。",
        label: "动态项最大 TTL",
        type: "number",
        default: 3600,
      },
      {
        key: "fixed_ttl",
        description: "为所有动态写入项指定固定 TTL。",
        label: "动态项固定 TTL",
        type: "number",
      },
      {
        key: "cleanup_on_shutdown",
        description: "控制插件退出时是否清理由其管理的条目。",
        label: "关闭时清理",
        type: "switch",
        default: true,
      },
    ],
  },
  {
    kind: "upgrade",
    type: "executor",
    name: "Upgrade",
    description: "执行 ForgeDNS 升级流程",
    icon: "ArrowUpRight",
    configSchema: [
      {
        key: "force",
        description:
          "即使目标 release 不比当前版本更新，也继续下载、校验并替换。",
        label: "强制升级",
        type: "switch",
        default: false,
      },
      {
        key: "cleanup",
        description: "升级成功后清理 cache_dir 和 backup_dir。",
        label: "升级后清理缓存",
        type: "switch",
        default: true,
      },
      {
        key: "repository",
        description: "GitHub 仓库。",
        label: "GitHub 仓库",
        type: "text",
        default: "SvenShi/forgedns",
      },
      {
        key: "asset",
        description: "Release asset 名称；auto 会按当前平台选择 archive。",
        label: "Release Asset",
        type: "text",
        default: "auto",
      },
      {
        key: "cache_dir",
        description: "下载缓存目录。",
        label: "下载缓存目录",
        type: "text",
        placeholder: "./upgrade/cache",
      },
      {
        key: "backup_dir",
        description: "替换前备份目录。",
        label: "备份目录",
        type: "text",
        placeholder: "./upgrade/backups",
      },
      {
        key: "restart",
        description:
          "设置为 service 时，升级成功替换二进制文件后应用会主动退出并返回错误码，以便 systemd 自动重启。",
        label: "重启策略",
        type: "select",
        options: [
          { label: "None", value: "none" },
          { label: "Service", value: "service" },
        ],
      },
      {
        key: "timeout",
        description: "与 CLI upgrade 参数含义一致。",
        label: "超时",
        type: "duration",
        default: "30s",
      },
      {
        key: "socks5",
        description: "与 CLI upgrade 参数含义一致。",
        label: "SOCKS5 代理",
        type: "text",
        placeholder: "127.0.0.1:1080",
      },
      {
        key: "insecure_skip_verify",
        description: "与 CLI upgrade 参数含义一致。",
        label: "跳过 HTTPS 证书校验",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "download",
    type: "executor",
    name: "Download",
    description: "下载 HTTP/HTTPS 文件到本地目录并原子覆盖",
    icon: "File",
    configSchema: [
      {
        key: "downloads",
        description:
          "下载一个或多个 http/https 文件到本地目录，并在新内容完整写入后覆盖目标文件。",
        label: "下载项",
        type: "array",
        required: true,
        placeholder:
          '[{"url":"https://example.com/geosite.dat","dir":"/etc/forgedns","filename":"geosite.dat"}]',
        item: {
          type: "object",
          label: "下载项",
          summaryFields: ["filename", "url"],
          fields: [
            {
              key: "url",
              description: "下载项的 http/https URL。",
              label: "URL",
              type: "text",
              required: true,
              placeholder: "https://example.com/geosite.dat",
            },
            {
              key: "dir",
              description: "下载项的目标目录。",
              label: "目录",
              type: "text",
              required: true,
              placeholder: "/etc/forgedns",
            },
            {
              key: "filename",
              description: "下载项的目标文件名。",
              label: "文件名",
              type: "text",
              placeholder: "geosite.dat",
            },
          ],
        },
      },
      {
        key: "timeout",
        description: "下载超时时间。",
        label: "超时",
        type: "duration",
        default: "30s",
      },
      {
        key: "socks5",
        description: "所有下载连接都会通过该 SOCKS5 代理发起。",
        label: "SOCKS5 代理",
        type: "text",
        placeholder: "127.0.0.1:1080",
      },
      {
        key: "startup_if_missing",
        description: "启动时检查目标文件，缺失项会在其它插件初始化前自动下载。",
        label: "启动时补齐缺失文件",
        type: "switch",
        default: true,
      },
    ],
  },
  {
    kind: "reload_provider",
    type: "executor",
    name: "Reload Provider",
    description: "按 tag 定向刷新一个或多个 provider",
    icon: "RefreshCw",
    configSchema: [
      stringArrayField(
        "args",
        "Provider 引用",
        "$geosite_cn\n$geoip_cn",
        true,
        "按 args 中声明顺序逐个执行 targeted provider reload。",
        {
          type: "reference",
          referenceTypes: ["provider"],
          referencePrefix: "$",
          placeholder: "geosite_cn",
        },
      ),
    ],
  },
  {
    kind: "reload",
    type: "executor",
    name: "Reload",
    description: "触发一次应用级全量 reload",
    icon: "RefreshCw",
    configSchema: [],
  },
  {
    kind: "cron",
    type: "executor",
    name: "Cron",
    description: "后台按 cron 或固定间隔调度一组 executor",
    icon: "Clock",
    configSchema: [
      {
        key: "jobs",
        description: "定义一个或多个后台任务。",
        label: "任务列表",
        type: "array",
        required: true,
        placeholder:
          '[{"name":"refresh_sets","interval":"5m","executors":["$seq_refresh"]}]',
        item: {
          type: "object",
          label: "任务",
          summaryFields: ["name", "interval", "schedule"],
          fields: [
            {
              key: "name",
              description: "任务名称，用于日志与运行时标识。",
              label: "任务名称",
              type: "text",
              required: true,
              placeholder: "refresh_sets",
            },
            {
              key: "schedule",
              description: "使用标准 5 字段 cron 表达式调度任务。",
              label: "Cron 表达式",
              type: "text",
              placeholder: "0 */6 * * *",
            },
            {
              key: "interval",
              description: "用简单固定间隔调度任务。",
              label: "固定间隔",
              type: "duration",
              placeholder: "5m",
            },
            {
              key: "executors",
              description: "定义任务触发时顺序执行的 executor 列表。",
              label: "执行器",
              type: "array",
              required: true,
              placeholder: "$seq_refresh\ndebug_print cron refresh",
              itemOptions: [
                executorReferenceArrayItem("seq_refresh"),
                inputArrayItem("debug_print cron refresh"),
              ],
            },
          ],
        },
      },
      {
        key: "timezone",
        description: "为当前 cron 插件下的所有 schedule 任务指定时区。",
        label: "时区",
        type: "text",
        placeholder: "Asia/Shanghai",
      },
    ],
  },
];
