import type { PluginKindDefinition } from "./shared";
import { executorRef } from "./shared";

export const serverPluginDefinitions: PluginKindDefinition[] = [
  {
    kind: "udp_server",
    type: "server",
    name: "UDP Server",
    description: "标准 DNS UDP 入口，把请求交给指定执行器",
    icon: "Wifi",
    configSchema: [
      executorRef(
        "entry",
        "入口执行器",
        true,
        undefined,
        "指定处理该监听器全部请求的入口执行器，通常为sequence插件。",
      ),
      {
        key: "listen",
        description: "指定 UDP 监听地址。",
        label: "监听地址",
        type: "text",
        placeholder: "0.0.0.0:53",
        required: true,
      },
    ],
  },
  {
    kind: "tcp_server",
    type: "server",
    name: "TCP / DoT Server",
    description: "DNS over TCP；配置证书后作为 DoT 入口",
    icon: "Network",
    configSchema: [
      executorRef(
        "entry",
        "入口执行器",
        true,
        undefined,
        "指定 TCP 或 DoT 请求进入策略链时使用的入口执行器。",
      ),
      {
        key: "listen",
        description: "指定 TCP 监听地址。",
        label: "监听地址",
        type: "text",
        placeholder: ":53",
        required: true,
      },
      {
        key: "cert",
        description: "指定 TLS 证书文件路径。",
        label: "TLS 证书",
        type: "text",
        placeholder: "/etc/forgedns/server.crt",
      },
      {
        key: "key",
        description: "指定 TLS 私钥文件路径。",
        label: "TLS 私钥",
        type: "text",
        placeholder: "/etc/forgedns/server.key",
      },
      {
        key: "idle_timeout",
        description: "指定连接空闲超时设置。",
        label: "空闲超时(秒)",
        type: "number",
        default: 10,
      },
    ],
  },
  {
    kind: "http_server",
    type: "server",
    name: "HTTP / DoH Server",
    description: "DNS over HTTPS，支持路径到执行器的多入口映射",
    icon: "Lock",
    configSchema: [
      {
        key: "entries",
        description: "定义 HTTP 路径到执行器的映射关系。",
        label: "路径映射",
        type: "array",
        required: true,
        placeholder: '[{"path":"/dns-query","exec":"seq_main"}]',
        item: {
          type: "object",
          label: "路径映射",
          summaryFields: ["path", "exec"],
          fields: [
            {
              key: "path",
              description: "指定 DoH 请求路径。",
              label: "路径",
              type: "text",
              required: true,
              placeholder: "/dns-query",
            },
            {
              key: "exec",
              description: "指定处理该路径请求的执行器。",
              label: "执行器",
              type: "reference",
              required: true,
              referenceTypes: ["executor"],
              referencePrefix: "",
              placeholder: "seq_main",
            },
          ],
        },
      },
      {
        key: "listen",
        description: "指定 HTTP/HTTPS 监听地址。",
        label: "监听地址",
        type: "text",
        placeholder: ":443",
        required: true,
      },
      {
        key: "src_ip_header",
        description: "指定从请求头中读取真实客户端来源地址的字段名。",
        label: "来源 IP Header",
        type: "text",
        placeholder: "X-Forwarded-For",
      },
      {
        key: "cert",
        description: "指定 HTTPS 证书文件路径。",
        label: "HTTPS 证书",
        type: "text",
        placeholder: "/etc/forgedns/server.crt",
      },
      {
        key: "key",
        description: "指定 HTTPS 私钥文件路径。",
        label: "HTTPS 私钥",
        type: "text",
        placeholder: "/etc/forgedns/server.key",
      },
      {
        key: "idle_timeout",
        description: "指定 HTTP 连接空闲超时。",
        label: "空闲超时(秒)",
        type: "number",
        default: 30,
      },
      {
        key: "enable_http3",
        description: "指定是否同时启用 HTTP/3。",
        label: "启用 HTTP/3",
        type: "switch",
        default: false,
      },
    ],
  },
  {
    kind: "quic_server",
    type: "server",
    name: "QUIC / DoQ Server",
    description: "DNS over QUIC 入口",
    icon: "Shield",
    configSchema: [
      executorRef(
        "entry",
        "入口执行器",
        true,
        undefined,
        "指定 DoQ 请求进入策略链时使用的入口执行器。",
      ),
      {
        key: "listen",
        description: "指定 QUIC 监听地址。",
        label: "监听地址",
        type: "text",
        placeholder: ":853",
        required: true,
      },
      {
        key: "cert",
        description: "指定 DoQ 所需 TLS 证书文件。",
        label: "TLS 证书",
        type: "text",
        placeholder: "/etc/forgedns/server.crt",
        required: true,
      },
      {
        key: "key",
        description: "指定 DoQ 所需 TLS 私钥文件。",
        label: "TLS 私钥",
        type: "text",
        placeholder: "/etc/forgedns/server.key",
        required: true,
      },
      {
        key: "idle_timeout",
        description: "指定 QUIC transport 的空闲超时。",
        label: "空闲超时(秒)",
        type: "number",
      },
    ],
  },
];
