# ForgeDNS example configuration file
#
# See full examples and documentation at:
# https://forgedns.cn

log:
  level: info

plugins:
  # Forward to upstream DNS servers
  - tag: forward
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "223.5.5.5"
        - addr: "8.8.8.8"

  - tag: main_sequence
    type: sequence
    args:
      - exec: $forward
      - exec: accept

  # UDP server listening on :5335
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":5335"

  # TCP server listening on :5335
  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":5335"
