blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/SvenShi/forgedns/discussions
    about: Ask questions, share ideas, or discuss usage here.
  - name: Documentation
    url: https://www.forgedns.cn
