plugins:
  - tag: forward
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "223.5.5.5"


  - tag: "udp_server"
    type: "udp_server"
    args:
      entry:  "forward"
      listen:  ":5335"
